### ISSUE TITLE
生成图片花费时间太长

### ISSUE THREAD

**Issue by 9ayhub** [eyounx/ASG#2]
俞教授您好！请问使用代码里的参数，要多久才能跑完呢？我尝试了一下，几个小时都没有跑完，这是正常的吗？有什么办法提升速度吗？

**Comment by eyounx** [comment]
> 俞教授您好！请问使用代码里的参数，要多久才能跑完呢？我尝试了一下，几个小时都没有跑完，这是正常的吗？有什么办法提升速度吗？

由于使用的是非梯度优化，实验时间确实比较长。要么用更多的机器来加速优化，要么改为梯度优化的方法。
